// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL =
      `postgresql://${process.env.POSTGRES_USER}:` +
      `${encodeURIComponent(process.env.POSTGRES_PASSWORD!)}@` +
      `${process.env.POSTGRES_HOST}:${process.env.POSTGRES_PORT}/` +
      `${process.env.POSTGRES_DATABASE}?schema=public`,
  },
});
